### ISSUE TITLE
Issue on 4.3.2 version

### ISSUE THREAD

**Issue by breim** [FortAwesome/font-awesome-sass#87]
Hello, 

After update to 4.3.2, i got this error :

undefined method `key?' for nil:NilClass

I back to 4.3.0 and no more errors.
Rails version 4.1.6 and ruby 2.1.3

Thx

**Comment by zxlai** [comment]
I got same errors in this version.

**Comment by zxlai** [comment]
I create a pull request. #88

**Comment by JonasBorchelt** [comment]
yup, same here!

**Comment by supercodepoet** [comment]
Sorry guys I was trying to get some PRs in and didn't look too heavily at them. I had a little time and wanted to get caught up. Will take closer look into the future. This should be fixed in #89
